### ISSUE TITLE
Forms.php into an include file for functions.php

### ISSUE THREAD

**Issue by rcass** [redacademy/kin-summer-2017#1]
Hey @markfloress,

According to the [documentation](https://www.gravityhelp.com/documentation/article/gform_pre_render/) that function should be located in the functions.php (look towards the bottom of the article).

What I suggest is just making the forms.php an include files that function.php calls (see line 129 for extra.php). Basically by making it an include file it will prevent the file from getting too long and unmanageable.

**Comment by markfloress** [comment]
done!
